[package]
name = "archea"
version = "0.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

bevy = "0.13.0"
bevy_panorbit_camera = "0.16.0"
rand = "0.9.0-alpha.0"
